# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-25 18:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=32)),
                ('response', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('user', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('pwd', models.CharField(max_length=32)),
                ('sex', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=32)),
                ('major', models.CharField(max_length=32)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('user', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('pwd', models.CharField(max_length=32)),
                ('sex', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=32)),
                ('text', models.TextField()),
                ('advice', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Family_Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=32)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='private_doctor.Family')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='private_doctor.Doctor'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='private_doctor.Family'),
        ),
    ]
