# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-26 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='major',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
